image: marcoturi/ionic2-boilerplate:master

stages:
  - test
  - deploy

before_script:
  - npm prune
  - npm install
  - gem install scss_lint
  - export DISPLAY=:99

cache:
  paths:
    - node_modules/

build_web:
  stage: test
  only:
      - master
  script:
    - npm run lint
    - npm run scss-lint
    - ./node_modules/.bin/webdriver-manager update
    - /usr/bin/Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &
    - mkdir coverage
    - npm run test
    - npm run build
    - npm run e2e

build_android:
  stage: deploy
  only:
    - master
  script:
    - ionic state restore
    - npm run android:release
    - ls ./platforms/android/build/outputs/apk/android*.apk
  artifacts:
    paths:
      - platforms/android/build/outputs/apk/
